sudo: required
services:
  - docker
after_success:
  - docker build -t apawlak/comics-gui .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push apawlak/comics-gui
