sudo: required
services:
  - docker
before_install:
  - docker build -t pawlakadam/comics-gui -f Dockerfile.dev .
language: generic
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-comics"
  env: "Dockercomics-env"
  bucket_name: "elasticbeanstalk-us-east-2-377048122373"
  bucket_path: "docker-comics"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: AWS_SECRET_KEY
