FROM node:10.14.1

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm install -g npm@6.4.1

COPY . /user/src/app

CMD ["npm","start"]

CMD ["ng","serve", "--host", "0.0.0.0"]


FROM node:10.14.1

WORKDIR '/app'

COPY package.json .

RUN npm install -g npm@6.4.1

COPY . .

CMD ["npm","run", "start"]


FROM node:lts-alpine

WORKDIR /app

COPY package.json ./

RUN npm install -g @angular/cli
RUN npm install

COPY . .
EXPOSE 4200
CMD ["ng","serve", "--host", "0.0.0.0"]
