version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - 4200:4200
    volumes:
      - /app/node-modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node-modules
      - .:/app
    command: ["npm", "run", "test"]
